from langchain_google_genai import ChatGoogleGenerativeAI
from prompts.summarization_prompt import *
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

def summarize_research_papers(docs):
    """
    Summarizes research papers using a generative AI model.

    Args:
        docs: The documents containing research paper content.

    Returns:
        The summary generated by the AI model.
    """
    try:
        # Initialize the AI model
        model = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
        
        # Format the prompt with the content of the documents
    
        final_prompt = summarization_prompt.format(context=docs[0].page_content)

        # print(final_prompt)
        
        # Generate and return the summary
        return model.invoke(final_prompt)
    
    except Exception as e:
        # Handle exceptions and print the error message
        print(f"An error occurred while summarizing: {e}")
       